name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

  # Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.6
      endpoint: statisticsnorway (6)

pool:
  vmImage: 'ubuntu-latest'

variables:

  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter

  # Variables defined here
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: project
    value: 'dapla'
  - name: imageNameClient
    value: 'eu.gcr.io/prod-bip/ssb/dapla/rawdata/rawdata-collection-client'
  - name: imageNameClientProxy
    value: 'eu.gcr.io/prod-bip/ssb/dapla/rawdata/rawdata-collection-client-proxy'
  - name: repoNameClient
    value: 'prod-bip/ssb/dapla/rawdata/rawdata-collection-client'
  - name: repoNameClientProxy
    value: 'prod-bip/ssb/dapla/rawdata/rawdata-collection-client-proxy'
  - name: artifactName
    value: 'rawdata-collection-project'
  - name: artifactNameClient
    value: 'rawdata-collection-client'
  - name: mavenContainer
    value: 'maven:3.6.3-openjdk-15'
  - name: checkStyleRunAnalysis
    value: 'false'
  - name:  MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

jobs:
  - job: buildTestPublishToPipeline
    displayName: 'Compile and deploy app'
    container: ${{ variables.mavenContainer }}

    # Job condition: Run these jobs on any branch, but not on tags
    condition:  not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

    # Steps in this job
    steps:

      # Authenticate Maven to Nexus using predefined Service Connections
      # (Project Settings->Pipelines->Service Connections)
      - template: maven/task-authenticate.yml@templates

      - template: maven/task-cache.yml@templates

      - template: maven/task-test-and-verify.yml@templates
        parameters:
          checkStyleRunAnalysis: ${{ variables.checkStyleRunAnalysis }}

      - template: maven/task-sonar-analyze.yml@templates

      - task: Maven@3
        displayName: 'Maven install and deploy'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'deploy'
          options: 'clean verify -DskipTests=true -Dmaven.javadoc.skip=true -U -P ssb-bip --batch-mode -Djdk.tls.client.protocols="TLSv1.2" $(MAVEN_OPTS)'

      - bash: |
          mkdir target

      # Publish pipeline artifact
      - publish: target
        displayName: 'Publish artifact to pipeline'
        artifact: ${{ variables.artifactName }}

  - job: buildClientModuleDockerFile
    dependsOn: buildTestPublishToPipeline
    steps:

    # Download pipeline artifact
    - download: current
      displayName: 'Download pipeline artifact'
      artifact: ${{ variables.artifactNameClient }}

    # Copy pipeline artifact into working directory
    - task: CopyFiles@2
      inputs:
        contents: '$(Pipeline.Workspace)/${{ variables.artifactNameClient }}/*.jar'
        targetFolder: './target'
    - task: CopyFiles@2
      inputs:
        contents: '$(Pipeline.Workspace)/${{ variables.artifactNameClient }}/libs/*'
        targetFolder: './target/libs'
    - task: CopyFiles@2
      inputs:
        contents: '$(Pipeline.Workspace)/${{ variables.artifactNameClient }}/classes/*.xml'
        targetFolder: './target/classes'
    - task: CopyFiles@2
      inputs:
        contents: '$(Pipeline.Workspace)/${{ variables.artifactNameClient }}/classes/*.yaml'
        targetFolder: './target/classes'

    - template: ${{variables['System.DefaultWorkingDirectory']}}/docker/docker-build-image-and-push-to-gcr.yml
      parameters:
        imageName: ${{ variables.imageNameClient }}
        repoName: ${{ variables.repoNameClient }}
  #- job: buildClientProxyDockerFile