name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

  # Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
  paths:
    exclude:
      - 'api/*'
      - 'bong/*'
      - 'client/*'

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.6
      endpoint: statisticsnorway (6)

pool:
  vmImage: 'ubuntu-latest'

variables:

  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter

  # Variables defined here
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: project
    value: 'dapla'
  - name: imageHost
    value: 'https://eu.gcr.io/'
  - name: imageName
    value: 'eu.gcr.io/prod-bip/ssb/dapla/rawdata/rawdata-collection-project'
  - name: repoName
    value: 'prod-bip/ssb/dapla/rawdata/rawdata-collection-project'
  - name: artifactName
    value: 'rawdata-collection-project'
  - name: mavenContainer
    value: 'maven:3.6.3-openjdk-15'
  - name: checkStyleRunAnalysis
    value: 'false'
  - name:  MAVEN_CACHE_FOLDER
    value: $(Pipeline.Workspace)/.m2/repository
  - name: MAVEN_OPTS
    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

jobs:
  - job: mavenBuildTestPublish
    displayName: 'Compile and deploy app'
    container: ${{ variables.mavenContainer }}

    # Job condition: Run these jobs on any branch, but not on tags
    condition:  not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

    # Steps in this job
    steps:

      # Authenticate Maven to Nexus using predefined Service Connections
      # (Project Settings->Pipelines->Service Connections)
      - template: maven/task-authenticate.yml@templates

#      - template: maven/task-cache.yml@templates
#
#      - template: maven/task-test-and-verify.yml@templates
#        parameters:
#          checkStyleRunAnalysis: ${{ variables.checkStyleRunAnalysis }}
#
#      - template: maven/task-sonar-analyze.yml@templates
#
#      - task: Maven@3
#        displayName: 'Maven install and deploy'
#        inputs:
#          mavenPomFile: 'pom.xml'
#          mavenOptions: '-Xmx3072m'
#          jdkArchitectureOption: 'x64'
#          publishJUnitResults: false
#          testResultsFiles: '**/TEST-*.xml'
#          goals: 'deploy'
#          #options: 'clean verify dependency:copy-dependencies -DskipTests=true -Dmaven.javadoc.skip=true -U -P ssb-bip --batch-mode -Djdk.tls.client.protocols="TLSv1.2" $(MAVEN_OPTS)'
#          options: 'clean verify -DskipTests=true -Dmaven.javadoc.skip=true -U -N -P ssb-bip --batch-mode -Djdk.tls.client.protocols="TLSv1.2" $(MAVEN_OPTS)'
#
# TODO: cleanup- variables commented out code
#
      - task: Maven@3
        displayName: 'Maven deploy of the project root/base pom.xml file'
        inputs:
          goals: 'deploy:deploy-file'
          options: '-N -Dfile=pom.xml -DpomFile=pom.xml ssb-bip -Durl=https://nexus.prod-bip-ci.ssb.no/repository/maven-snapshots/ -DgeneratePom=false -DrepositoryId=bip-nexus-snapshots'

      # Publish pipeline artifact
      - publish: target
        displayName: 'Publish artifact to pipeline'
        artifact: ${{ variables.artifactName }}

   #dockerfile 1
      #flytte filer
        #3 submoduler
        #1 el 3artifacts?
      #vulner check
   #dockerfile 2
     #vulner check
